### ISSUE TITLE
ECMP for ns2

### ISSUE THREAD

**Issue by ChengjunJia** [baiwei0427/MQ-ECN#1]
Hello, 白神。我尝试仿真FatTree拓扑(100Gbps/1us)下的XCP性能，因为需要ECMP来支持多路径，我patch了`mqecn.patch`. 
我做了如下设置：
```
$ns rtproto DV
Agent/rtProto/DV set advertInterval 0.0001
Node set multiPath_ 1
```
按照WebServer的CDF产生的流量是从1ms开始（等DV路由协议在0.1ms的时候触发后进入收敛状态）。
我抓了MultiPathForwarder的classify函数的log，能明确看到通往同一个dstIP的pkt（具有不同的srcIP和flowId），返回的cl值是不同的（我设置的FatTree中ToR和Agg Switch之间是4个一组，我能看到cl的值是0-3之间）；我认为流量已经成功通过ECMP做了负载均衡。
但是我仍然发现，使用FatTree拓扑会产生丢包；而如果把FatTree拓扑中的ToR-Agg Switch之间的多路径合并成一条路径（链路带宽对应扩大），仿真是不会有丢包。

我想请教一下，怎么确认，我运行中的流量确实走了多路径呢？（只抓classify函数的返回值是不是可能有问题？）

**Comment by baiwei0427** [comment]
我记得enable ECMP还需要设置perflow_ 1，如果不设置这个，那么数据包应该是per packet ECMP。
另外，FatTree肯定在任何地方都可能丢包，这个是没办法的。
走多路径最简单的办法就是测多个flows的aggregate throughput，看看是不是远远超过一条链路的带宽。

**Comment by baiwei0427** [comment]
> Hello, 白神。我尝试仿真FatTree拓扑(100Gbps/1us)下的XCP性能，因为需要ECMP来支持多路径，我patch了`mqecn.patch`.
> 我做了如下设置：
> 
> ```
> $ns rtproto DV
> Agent/rtProto/DV set advertInterval 0.0001
> Node set multiPath_ 1
> ```
> 
> 按照WebServer的CDF产生的流量是从1ms开始（等DV路由协议在0.1ms的时候触发后进入收敛状态）。
> 我抓了MultiPathForwarder的classify函数的log，能明确看到通往同一个dstIP的pkt（具有不同的srcIP和flowId），返回的cl值是不同的（我设置的FatTree中ToR和Agg Switch之间是4个一组，我能看到cl的值是0-3之间）；我认为流量已经成功通过ECMP做了负载均衡。
> 但是我仍然发现，使用FatTree拓扑会产生丢包；而如果把FatTree拓扑中的ToR-Agg Switch之间的多路径合并成一条路径（链路带宽对应扩大），仿真是不会有丢包。
> 
> 我想请教一下，怎么确认，我运行中的流量确实走了多路径呢？（只抓classify函数的返回值是不是可能有问题？）

我记得enable ECMP还需要设置perflow_ 1，如果不设置这个，那么数据包应该是per packet ECMP。
另外，FatTree肯定在任何地方都可能丢包，这个是没办法的。
走多路径最简单的办法就是测多个flows的aggregate throughput，看看是不是远远超过一条链路的带宽。

**Comment by ChengjunJia** [comment]
perflow_ 1这个我参考白神的脚本也set过了。谢谢白神提醒，我测一下aggregate throughput看看

我跑HPCC的那套ns3代码的时候， FatTree拓扑下的DCTCP是没有触发PFC的；我理解在ns2中把DropTail设置的稍高（5MB），合适的拥塞控制算法就应该没有丢包了？白神之前跑的DCTCP实验是仍然会有丢包么？

**Comment by baiwei0427** [comment]
> perflow_ 1这个我参考白神的脚本也set过了。谢谢白神提醒，我测一下aggregate throughput看看
> 
> 我跑HPCC的那套ns3代码的时候， FatTree拓扑下的DCTCP是没有触发PFC的；我理解在ns2中把DropTail设置的稍高（5MB），合适的拥塞控制算法就应该没有丢包了？白神之前跑的DCTCP实验是仍然会有丢包么？

加我微信私聊。
